apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-web-app
  template:
    metadata:
      labels:
        app: react-web-app
    spec:
      containers:
      - name: react-web-app
        image: react-web-app
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
